dist: trusty
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-3.9
          packages:
            - clang-3.9
      env:
         - MATRIX_EVAL="CC=clang-3.9 && CXX=clang-3.9"
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
         - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - eval "${MATRIX_EVAL}"

install:
  - sudo apt-get install qtbase5-dev

script:
  - ./travis-ci/build.bash

