language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - libgtk2.0-dev
      - libasound2-dev
      - libjack-dev

script:
  - bash scripts/cmake-build.sh

