dist: trusty
language: c
compiler:
- gcc
- clang
before_install:
- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
- sudo add-apt-repository --yes ppa:george-edison55/cmake-3.x
install:
- sudo apt-get install qtbase5-dev
- sudo apt-get install cmake
addons:
  apt:
    packages:
    - sshpass
    - libasound2-dev
script:
- bash travis-ci/build.bash
after_success:
- openssl aes-256-cbc -K $encrypted_7827771acbce_key -iv $encrypted_7827771acbce_iv
  -in travis-ci/deploy_rsa.enc -out travis-ci/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 travis-ci/deploy_rsa
- export SSHPASS="$GNUITAR_DEPLOY_PASS"
- ssh-add travis-ci/deploy_rsa
- sshpass -e scp -v build/Gnuitar-0.4.0-Linux.tar.gz $GNUITAR_DEPLOY_USER@$GNUITAR_DEPLOY_HOST:$GNUITAR_DEPLOY_PATH/Gnuitar-0.4.0-Linux.tar.gz
env:
  global:
  - secure: YRyIdRBcqUrU90DO57f6o6ZDQSCJtRVEsJZQvlCBdCbVXbJt9LPkCRXOwxz6MlrEVktNOq3ZHWyTDNE/0hVYGYVeD/xFtiz7VpsjK6VhyjpCWbJi48v+3Sw/KrS8eAJ4zVJinRF2jb65H2s9o+31mj+JNtJv8Y6gAI/h2/29g717mrCJXbJR/f8dgojpahE19SeowFqrpGYlJf1vaBZXucVbYQnaN9V3IrYBiYvXkcDAYm8hf06b0UCIE1cr7Q49L05PR2d1dbkMgGUybdZGOGfVx3OTWz/zOv+NZtlRnk6KYBp7B5NevZ9LECBA5XRo0wF1EhQKnucgQMM75wXWUMiDUG3/wsX0+LzavoQfBuPOjgWBgFAA8yAWc3sGy6gMLrNA/85CZAKbB74lsLa8SwxEHPt1eyFkIxhKZrfvdazBOJhTdj46s/cZwOYlE1aBcsDvEsg450GhDH464YWoGrTPzfXfbK+AdUTJj9ytqkeR5yEU3mrYXlA0goHn+3CdQ6LlJdbL1qA9q/PrVN/MqKdNVUx9qAdRxlZp4zyU7gxCCYB43K/GX8+HjLM3F/yoNTvn+J8TgT3i90ve4Ut6HX6pHBeMCnZ4FEfu0bmhdj+rB9isL+1VedQQxECRnFNO9hQJinSZPHKyBpZJT/aNj7Se2X3viPe0pua6USJrhzI=
  - secure: CsdWL+Uf42kWW+f9bxYXKjUNlMlK20+voFEW9AZMt1Hcr5wQID5vKrKy37V/1NGCP3fZ0mgHaqy+yb6Lm91X1MYt4oFkyimfDRv/3HmLSombr4JZKH/6QD9r5Qrj7XGGt6ZK0TvzZpxQNTAvLEEWPhGoEKGr+wljE3ypC80nCunXQlo5MfdjVaE+OxaGQJ8A0WzcrqZYWCGt/DbENARSQflp2n3vRpZsnMWJAdOFOmQ29f9FvxXFbaSe7gsGwEdv9tb1fqXujRLDUfcW8ZgVvallPOrHLKFjWo5o9/G4ciK54gybKntU8Wzm8L9pG+CHCNU43RzStN8Wgwxbt9ZgHiG5KFCc2WpBTn0bX7J6EMnK/B8W3jH7wG1jmT/j44KWCRahktAOiGbq4cEXzTeuLiTDL7Y/KaoyooyLTOzlGi6OMdMwMVyNB5OrJA9po3y+uhN61hCXsJ+7j5IXmNySbrKgBpqr0xH0FKuphZhXAVh/LN9wgVhIRzspThQzc/jl5n4pUX/fOqbXeFCMCudkPYfmjYXjOf8SIaeJQHoFzQ6iWiKv/wJ5/yH6v4osyrxIOZoZlAhL+hRXS/eCzsitjs14ZRgtwbeGdfsVOubn/oakLAHqQQHLLZBlcO9DO6vc8Ch4Lhddy4nhSASgmTeWINDZPhvWwUV6gZO8CFdZ/ns=
  - secure: WJeFJUsgB0MdAQFDRYiA4YIYduXFyQXpD+Y1VkbTA86ETXVljXefBV3sf+3kIE5utFdmEFIX/M8lPP2hCoWFfUn7Tes3KztOGkHD24cc/MUAzM+D+y/nOzRT8ibhZYp7QGMOQSx9L2wwxpJFHbyKze5sHb6cgoXq4+V10ZbjSPFgxkyfkjZaXh2IZoNvIUiqDmYbyDTMXEBV4Lnezpzgf1ODgBu/9mazqB1E6C2cT9xKpI5Qw9eGgp/SYQD3nToOTo0I4S29EpJ3hd9eJaFwZNYhzkxsF7VbbU890XBgHA2cfZGQy4ORF0HcbGIVKNSZFWQFJW6VXL177dIxYDzC2lOMGZkEaaIq/iS+QjzhDTYBYIB7ZXZfiwe9HTccHPlx0HZt16J/TuCUfesO022kSnC5HpCCufpbwrtprYs3vub8bT1NDXDmeq1SDjJsvFGJ7CUA1IPaMUHg1nxut2ABKRytpE6pNLryRDDD7V24d7s+xBk2ZyLdcb4twxU+2aKvoUyCBtL57OH2Rk6j9SRm06aZaNcsfX8/Exs5jUNn7s1LPH084N7kENi3BHrs9a/Ixq3nKErp29h6BJf8hCFqVtiWZJsF1OWX+sDNsVB27xWlYy8Pp9MwubTOCjOHLQkLrBsJgnNyjPBaxtFOjKZEqJb0cK+lNBquDggIxbEJAic=
  - secure: tiJofdCrUZB/H6LxVwj/Dmn6w/zkSkCqQimZSj6NuNcfrezMCSOXVOvDXGOK0t/4uC2vCMIZ11a3200ptUwMMFFBW+VFYiJwLA4ZT5xaVZQKavpdyBilhGubFL6/6s++onmc16UxAvVHUpK7UnZGNyH5sc+y3b0xOuoRO4yicsqIAzB0PmMAvIuHlJxThTickYUl+AJ7WmsP2tK25SnY2Mc1dhCxu3S8Zyfr3g8bHIz9E3BTK4f3jyEMJzRPaX/xWSnbf1x1BTcMWeuR8blEAnctpiQfol1uHoopg6Sp6ZTOKJe8mxaLoKNr7xpWuDXXQeBQrKlI4g5OkSDPcs0FZmPzNaU48Lks5WXL0+wEkJmZJL1nP9TetvAoPYyb0L8gH/yAkJRK2ADnV8AL9aQjkqin9Utg/zyWR5O9zs++NYKJj0RNEXGCYCICE3Xyhh5OYhAIDlYLOYjJaO0wk+o1d/qgW3yyCcoLp8Y+cM+DGJPa3QU2AfjwRECRBwgmi12Pe3nKjxb9zmje8nRf62ZXYTxoiDIYwR/fDJWESSJV1iMENtwr92kp8mGl93MLbLrc2Im30G94CSMXa1X/q4ymqqhgpYB/3ix+uy14CwfR4++vwn50711GxLcHXyL7qxzah6FcpJ7FSOqiZHk7bntAjLYijwoDIoldXK/mbPeJ1kc=
