dist: trusty
language:
- c
- cpp
compiler:
- clang
- gcc
before_install:
- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
install:
- sudo apt-get install qtbase5-dev
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - libasound2-dev
    - gcc-6
    - g++-6
    - clang-3.6
script:
- bash travis-ci/build.bash

