dist: trusty
language: cpp
compiler:
- clang
- gcc
before_install:
- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
install:
- sudo apt-get install qtbase5-dev
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-3.9
    packages:
    - g++-7
    - clang-3.9
script:
- bash travis-ci/build.bash

