platform: x64
configuration: Release
before_build:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
build:
  project: build\ALL_BUILD.vcxproj
